# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, CNN ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ody55eus/flowers

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Get Images
      run: |
        mv /root/data .
        mkdir output
    - name: Run data preparation
      run: |
        cd scripts
        python data_preparation.py
        python cnn_split_test_val.py
        cd ..
#    - name: Run cnn training
#      run: |
#        cd scripts
#        python cnn_training.py
#        cd ..
    - name: Get Pretrained Model
      run: |
        mkdir model && cd model
        curl -c /tmp/cookies "https://drive.google.com/uc?export=download&id=1uxnup4oqr-FZZBUjrbIxyEKI20nXupth" > /tmp/intermezzo.html
        curl -L -b /tmp/cookies "https://drive.google.com$(cat /tmp/intermezzo.html | grep -Po 'uc-download-link" [^>]* href="\K[^"]*' | sed 's/\&amp;/\&/g')" > model1.zip
        unzip model1.zip
        wget -O model2.zip "https://drive.google.com/uc?export=download&id=1vv1E25qYOmy0I7U6tKRmGbeAB6v-Im4x"
        unzip model2.zip
        cd ..
    - name: Run cnn evaluation
      run: |
        cd scripts
        python cnn_evaluation.py
        cd ..
    - name: upload output
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output

